### ISSUE TITLE
甲骨文arm无法重装debian12 

### ISSUE THREAD

**Issue by niu12503** [leitbogioro/Tools#10]
![efac120b-b402-47ed-be4a-0fcbddc28bc7](https://user-images.githubusercontent.com/21340487/232217070-940a4490-6f31-442a-90e6-8e3cd4386186.png)
卡在这里不动

**Comment by leitbogioro** [comment]
稍等，我也发现了这个问题

**Comment by leitbogioro** [comment]
抱歉，一个判断逻辑出问题了，已经修复了，删掉脚本重新下载安装
