### ISSUE TITLE
cannot reinstall debian 10

### ISSUE THREAD

**Issue by crixsz** [leitbogioro/Tools#11]
After starting the installation process, the VPS shut down and I haven't been able to connect to it via SSH for over an hour now.My VPS provider is DigitalOcean. This is the details

Specs:
1 CPU
512MB 
 
Nothing came up on the recovery console whereas usually there is a graphical installation of the distro as I have tested for Debian 11

**Comment by leitbogioro** [comment]
Could you please provide me the details about this situation you met? like the following whole command:
bash InstallNET.sh -debian 10 -port "" -pwd '' -mirror "xxx"
show the VNC screen shot for me too if you can.

**Comment by crixsz** [comment]
i have used this command
``` 
bash InstallNet.sh -debian 10
````

this is the screenshot after the vps rebooted
![ssinstall](https://user-images.githubusercontent.com/89030463/235335204-bc111471-0b46-414d-b71c-0b7d19df1001.png)

and this is the recovery console
![qemu](https://user-images.githubusercontent.com/89030463/235335210-64061469-dd8f-4803-b8b3-ae6ea48e9b9b.png)

**Comment by leitbogioro** [comment]
I think I should enter the actual environment of DigitalOcean to figure what problem had happened. Could you providing IP, port, user, password etc. so that I can ssh to the server to troubleshoot the problems? this may not safe, but it's the most effective.

**Comment by leitbogioro** [comment]
I built a server that the hard spec is same to you in Singapore region of DigitalOcean, the original OS template is CentOS series. I tested whether the script can run in CentOS 8 and CentOS 9, due to the less memory, even "dnf install" can not run successfully, 

![图片](https://user-images.githubusercontent.com/22023450/235347783-fc6eb999-378e-48e7-8472-2d5a152d45d6.png)

**Comment by crixsz** [comment]
do you have telegram or any place to privately message?

**Comment by leitbogioro** [comment]
https://t.me/moricalau
