### ISSUE TITLE
今天重装不了

### ISSUE THREAD

**Issue by madlaxcb** [leitbogioro/Tools#13]
Ubuntu Server 20.04 LTS "Focal Fossa"重装为centos 8-stream
昨天能成功，今天提示Error: boot firmware of your system could not be confirmed!
Ubuntu 环境和硬盘分区都和昨天一样。

用过以下都一样
bash InstallNET.sh -centos 8-stream -raid "0" -firmware
bash InstallNET.sh -centos 8-stream -raid "0"

**Comment by leitbogioro** [comment]
raid 0 仅提供给 Debian，装 centos 加不加 raid 0 都无法生效
