### ISSUE TITLE
Vultr无法使用 自动 Raid0吗

### ISSUE THREAD

**Issue by kugimiya530** [leitbogioro/Tools#16]
bash InstallNET.sh -debian 11 -pwd '密码' -raid "0" 

这是我用的参数  到达切raid那边 会报错

这算是bug还是不支援呀  哥~

**Comment by leitbogioro** [comment]
raid 0 只对 Debian 10有效，对11不好使

**Comment by kugimiya530** [comment]
啊!  明白 难怪一直失败
谢谢回答

**Comment by leitbogioro** [comment]
有条件的话给我提供机器测试，我没有raid 0硬盘机器

**Comment by kugimiya530** [comment]
....哥你上一个回覆其实我没看到，不然我就提供了，你太给力了，这么久了还回覆了

感谢你

Molly Lau ***@***.***> 於 2023年6月27日 週二 下午9:01 寫道：

**Comment by kugimiya530** [comment]
目前没有用到vultr的地方

不过至少往前了一步

有你的努力真好。

Molly Lau ***@***.***> 於 2023年6月27日 週二 下午9:08 寫道：
