### ISSUE TITLE
请问可以支持自定义用户名吗？

### ISSUE THREAD

**Issue by Grouppppp** [leitbogioro/Tools#17]
不想用 root 用户，脚本可否支持自定义用户名呢？在用自定义用户名的时候，sshd_config 设置 PermitRootLogin 为 no

**Comment by leitbogioro** [comment]
如果不用root用户部署，系统安装文件写入后到后期需要网络配置阶段，可能会出现权限不足，无法写入的风险，所以你可以在装好后自己关闭root用户登陆，并自行新建普通账户

**Comment by Grouppppp** [comment]
部署不是在当前用户下吗，这时候应该还是 root 的。你是指重启后会有一部分部署吗？

**Comment by leitbogioro** [comment]
统一root用户可以规避很多意料之外的问题，没人能预料到重启后如果给普通用户会发生什么意外，没有必要逐个在目前支持的8类系统，十几个不同版本的系统之间做这种测试，这不属于我这个脚本安装完系统后出现的品质缺陷问题，所以暂时不会考虑自定义其他登陆用户的功能

**Comment by leitbogioro** [comment]
这是一个免费的产品，你需要对它的功能和效果拥有足够的了解和自己负责，想魔改也随你

**Comment by Grouppppp** [comment]
了解，我来深入学习一下大佬的脚本。之前用过的一个其他debian安装脚本支持自定义用户，确实测试工作量会少很多，以及 RHEL 系非 root 账号出现意料之外的问题的可能性也更高。

**Comment by Grouppppp** [comment]
测试了脚本，还是有些问题。
1、-pwd 和 -port 参数经常报错 invalid option
2、安装时提示错误的 Mirror list，安装 Ubuntu 和 Kali 都有

**Comment by leitbogioro** [comment]
> 测试了脚本，还是有些问题。
> 1、-pwd 和 -port 参数经常报错 invalid option
> 2、安装时提示错误的 Mirror list，安装 Ubuntu 和 Kali 都有

你怎么跑的？发一下运行脚本的完整命令

**Comment by leitbogioro** [comment]
指定参数时，系统发行版版本号得指定，英文文档读不明白可以开谷歌翻译，一个按钮的事
bash InstallNET.sh -kali "rolling" -pwd '1235467892' -port "45273"

**Comment by leitbogioro** [comment]
纯中文文档也有，论坛里，多善用搜索：
https://hostloc.com/forum.php?mod=viewthread&tid=1159839

**Comment by leitbogioro** [comment]
我乐意为求知的人解决问题，但不想成为衣来伸手饭来张口的保姆
