### ISSUE TITLE
DD Debian10和11每隔1小时准时关机或者重启

### ISSUE THREAD

**Issue by QeHaxdCp** [leitbogioro/Tools#18]
23.6月DD完系统后debian10 11 开机后1小时准时关机【其他系统没有测试】，并且必须通过vps面板重启才能正常使用。如果增加一个定时任务，比如定时55分钟自动重启下，那么重启5分钟后会再次自动重启一次，这次重启过后可以正常使用到下次定时任务执行前。换了其他DD系统的脚本后，每隔1小时自动重启的问题没有在发生。

用的DD命令是：bash InstallNET.sh -debian 10 -pwd '密码' -port "端口"
用的是AWS的机器DD的

5月份用这个命令DD的系统一切正常，没有发生1小时自动关机或者重启的问题。

**Comment by leitbogioro** [comment]
有联系方式吗？沟通解决一下

**Comment by leitbogioro** [comment]
![图片](https://github.com/leitbogioro/Tools/assets/22023450/b2782381-16ee-432b-b8a6-34d02f915b52)

我甲骨文的机器用这个脚本装完，已经开机一天多了，没有发现过重启，而且计划任务里的 acme 自动申请证书是我自己装好系统后搭建网站的时候装的，新系统里没有附带任何计划任务

**Comment by QeHaxdCp** [comment]
https://t.me/Huntkaka

确定是干净的系统

**Comment by leitbogioro** [comment]
经测试可能是aws迁移或母机造成的，，此问题为特例，不是脚本本身通病
