### ISSUE TITLE
请教甲骨文的IPV6本机本地回环网卡IP如何设置？

### ISSUE THREAD

**Issue by cnm105** [leitbogioro/Tools#19]
例如IPV6地址是2603:bd22:4503:356e:1001:1123:1231
是否IPV6本机本地回环网卡IP是2603:bd22:4503:356e::1
但是我设置了2603:bd22:4503:356e::1 
却PIng不通2603:bd22:4503:356e::1

**Comment by leitbogioro** [comment]
甲骨文ipv6是网关fe80开头的本地网卡，具体配置方法看这个帖子：https://hostloc.com/forum.php?mod=viewthread&tid=1178346

**Comment by cnm105** [comment]
请问是这个吗？
inet6 fe80::17ff:fe00:fc5d/64 scope link 
       valid_lft forever preferred_lft forever
UBUNTU配置的话
 routes:
            -   to: default
                via: 10.0.0.1
            -   to: default
                via: fe80::17ff:fe00:fc5d

**Comment by tlze** [comment]
# 先通过dhcp获取ipv6和网关
sudo dhclient -6 ens3
# 查询网关，一般是fe80开头
ip -6 route show default

**Comment by cnm105** [comment]
输入sudo dhclient -6 enp0s3
ip -6 route show default

显示的default via fe80::200:17ff:fe30:1b2 dev enp0s3 proto ra metric 1024 expires 8996sec pref medium
这个fe80::200:17ff:fe30:1b2直接填到本机本地回环网卡IP那吗？

**Comment by tlze** [comment]
yes

**Comment by cnm105** [comment]
谢谢大佬
但是用VPS去ping fe80::200:17ff:fe30:1b2
ping不通 不影响吧

**Comment by tlze** [comment]
换理网关应该是能ping通，没见过你这种情况。

**Comment by cnm105** [comment]
root@ubuntu:~# sudo dhclient -6 enp0s3
root@ubuntu:~# ip -6 route show default
default via fe80::200:17ff:fe30:1b2 dev enp0s3 proto static metric 1024 pref medium
root@ubuntu:~# ping fe80::200:17ff:fe30:1b2
PING fe80::200:17ff:fe30:1b2(fe80::200:17ff:fe30:1b2) 56 data bytes
^C
--- fe80::200:17ff:fe30:1b2 ping statistics ---
18 packets transmitted, 0 received, 100% packet loss, time 17396ms
大佬看看 ping ipv6.google.com没问题能ping通

**Comment by leitbogioro** [comment]
机器上如果没敏感数据，重装吧，比你自己手敲弄好快

**Comment by leitbogioro** [comment]
添加 --network "static" 就行了

**Comment by cnm105** [comment]
10.0.0.1 这个能ping通
重装的话--network "static"添加到末尾吧？

**Comment by leitbogioro** [comment]
是的，能行的话记得给我项目点个star

**Comment by cnm105** [comment]
谢谢大佬们指点！给大佬的项目点star了，刚刚也试着重装了
bash InstallNET.sh -ubuntu 22.04 -port "22" -mirror "https://mirror.kakao.com/ubuntu-releases/" --network "static"

麻烦大佬删了这个问题吧，网关忘记打码了。
