### ISSUE TITLE
arm也是一样的镜像地址吗？请问

### ISSUE THREAD

**Issue by himonster1** [leitbogioro/Tools#2]
国内的arm cpu 的vps用这个地址https://mirrors.tuna.tsinghua.edu.cn/debian/  dd吗

**Comment by leitbogioro** [comment]
暂不支持ARM

**Comment by leitbogioro** [comment]
现在支持了

**Comment by leitbogioro** [comment]
ARM 机器安装，参数填 arm64 即可。
Ubuntu 22.04 及以后版本或许以后再也不会支持了，简单来讲就是 Ubuntu 官方认为这种无人值守 preseed 方式性能太差，砍了。详情参见专栏文章：https://zhuanlan.zhihu.com/p/580612280 “附录”章，“探究不支持 Ubuntu 22.04 的原因”节。
Ubuntu 太能折腾人了，浪费时间在上面不值得，以后还是用 Debian 稳定版吧。

**Comment by himonster1** [comment]
谢谢 很酷

**Comment by leitbogioro** [comment]
硬件架构自动转换，不用填“arm64”了，脚本自动适配

**Comment by leitbogioro** [comment]
Ubuntu 22.04现已支持，欢迎安装使用
