### ISSUE TITLE
使用default username 和 password 无法登录。。

### ISSUE THREAD

**Issue by moxuanyuan** [leitbogioro/Tools#20]
arm server，最开始也是用这个脚本重装 debian11 ，刚刚又用这个脚本重装 ubuntu ，结果使用efault username 和 password 无法登录。。怎样办。。。

**Comment by leitbogioro** [comment]
Ubuntu 用户密码统一为：
root
LeitboGi0ro
端口随你原系统的，并不一定是22，注意

**Comment by moxuanyuan** [comment]
> 

我就是用 用户名 root 密码 LeitboGi0ro 登录不了。。

**Comment by leitbogioro** [comment]
给个tg私信联系

**Comment by leitbogioro** [comment]
[[ -z "$tmpWORD" || "$linux_relese" == 'alpinelinux' || "$targetRelese" == 'Ubuntu' ]] && tmpWORD='LeitboGi0ro'
myPASSWORD=$(openssl passwd -1 ''$tmpWORD'') 代码里就是这么写的，我甲骨文ARM机器测过无数遍，不太可能有错

**Comment by moxuanyuan** [comment]
> 终端提示什么？是密码错误还是端口不对？
我刚在控制面版重装ubuntu，然后再一用你的脚本重装，结果一样，终端提示 Access denied

重装前终端里显示如下
![](https://files.catbox.moe/c42mgz.png)

**Comment by leitbogioro** [comment]
![图片](https://github.com/leitbogioro/Tools/assets/22023450/08008da5-aa01-4a21-96ab-55677405c07a)
我这边也用arm机器测试中，等结果

**Comment by leitbogioro** [comment]
我用xshell连接机器，由于密码不能显示明文，但位数你看一下，和 LeitboGi0ro 是一致的：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/9ccff4cf-f651-435a-bd17-e390cf6a5613)

首次连接终端提示是否和服务器交换密钥：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/37d60a00-93e4-422a-bb10-f52d8af6334f)

登陆成功：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/a3223e3b-3d4a-4fd1-a1c0-ab2b6084642d)

**Comment by leitbogioro** [comment]
你用的是不是putty之类的终端？putty缺少某些和服务器的密钥交换算法，导致和服务器连接失败

**Comment by leitbogioro** [comment]
建议用终端软件使用xshell，putty经常出各种莫名其妙的兼容性问题，不好用

**Comment by leitbogioro** [comment]
把你使用的终端软件告诉我，我用那个终端软件连接一下试试

**Comment by leitbogioro** [comment]
![图片](https://github.com/leitbogioro/Tools/assets/22023450/0d87645c-73b5-47e6-9320-40bf31093f09)

经测试用putty也能连接，密码就是默认的 LeitboGi0ro，你应当用我建议你的终端连接一下试试

**Comment by leitbogioro** [comment]
你的问题解决了，你说的连不上，是因为你试图在连接中介系统AlpineLinux，此时Alpine正在dd Ubuntu镜像文件到机器硬盘里，中途请不要连接这个中介系统AlpineLinux，耐心等待dd命令完成，中介系统重启后就会从内存里消失，最后等硬盘里的Ubuntu系统初始化后再连接。
具体详情看这个帖子：
https://hostloc.com/thread-1159839-22-1.html

**Comment by moxuanyuan** [comment]
我早上又双用服务商的面板重装了 ubuntu，再用你写的脚本去重装 ubuntu ，结果还是一样无法使用default username & password 登录。

终端用了 windterm，mobaxterm 和服务商的web控制台去登录，都一样

![](https://files.catbox.moe/c42mgz.png)
![](https://files.catbox.moe/3x3yeb.png)
![](https://files.catbox.moe/ytm8xx.png)
![](https://files.catbox.moe/0wfolx.png)
![](https://files.catbox.moe/r6mv9v.png)
![](https://files.catbox.moe/yl21vy.png)

**Comment by moxuanyuan** [comment]
我手动设置密码都不行

bash InstallNET.sh -ubuntu 22.04 -port "22" -pwd "LeitboGi0ro"

**Comment by moxuanyuan** [comment]
我用你的脚本又又又重装了一次，这次重装成debian 12 ，没问题的，现在问题就是出现在重装ubuntu

**Comment by ryanbossom** [comment]
對，我也是用腳本重裝UBUNTU，炸@@不能進，當初在重裝的時候有用參數設自己的密碼，可是不論是預設的還是自己設的都不行

**Comment by Georgebobby** [comment]
我也是，甲骨文ARM系統，Connection failed: connection timed out.

**Comment by weiyunkj666** [comment]
一样，唉，很大概率出现什么密码都不顶用的状态

**Comment by pegguo** [comment]
我的也是甲骨文AMD主机，重装的debian12系统，用的finalshell软件提示交换密匙了，但是什么密码都无法登录
