### ISSUE TITLE
Invaild option: '-d'

### ISSUE THREAD

**Issue by jiangjiangflies** [leitbogioro/Tools#21]

**Comment by leitbogioro** [comment]
Please describe your problem clearly, for example, which OS? which step this error appeared? which result after this error?

**Comment by jiangjiangflies** [comment]
不好意思，我看的一些博客的教程参数是-d， -v等。仔细看了一下你这里的参数是全拼-debian，-version。

**Comment by leitbogioro** [comment]
是的，这里需要注意一下，中文文档参见：
https://hostloc.com/thread-1159839-1-1.html
https://www.nodeseek.com/post-9383-1

**Comment by leitbogioro** [comment]
> 不好意思，我看的一些博客的教程参数是-d， -v等。仔细看了一下你这里的参数是全拼-debian，-version。

机器 CPU 架构能智能检测并在不同大系 Linux 发行版之间转换，不用给

**Comment by leitbogioro** [comment]
没问题 issue 就关了，有问题再开新的，论坛里如果有号，直接回提问
