### ISSUE TITLE
为啥dd个centos7都要1.5G内存

### ISSUE THREAD

**Issue by zx5qzx7tie8g** [leitbogioro/Tools#23]
苦笑

**Comment by leitbogioro** [comment]
自己去好好读原文：
《实现 Ubuntu 22.04 及以后版本安装的技术原理以及我对“原生网络安装”和“dd 安装”的观点与评价》
https://www.nodeseek.com/post-9558-1

**Comment by leitbogioro** [comment]
如果想在内存不符合脚本自动判断的目标机器上强装，可以指定 --nomemcheck 跳过内存检查，安装不保证能成功：
```bash InstallNET.sh -centos 7 --nomemcheck```

**Comment by zx5qzx7tie8g** [comment]
好的谢谢啦
