### ISSUE TITLE
Google Cloud Platform dd失联

### ISSUE THREAD

**Issue by RyanY610** [leitbogioro/Tools#24]
bash InstallNET.sh -debian 12 -version 64 -port 22 -pwd Ryan1995 -timezone Asia/Shanghai --network static/manual

Google Cloud Platform 用这个命令失联了，请告诉我怎么更改 ，是不是必须指定ip掩码这些，我看说明 可以通过 --network static/manual 自动获取。

**Comment by leitbogioro** [comment]
`bash InstallNET.sh -debian 12 -port "22" -pwd 'Ryan1995' -timezone "Asia/Shanghai" --network "static"`

**Comment by leitbogioro** [comment]
-version 参数已被废弃，--network static 或 manual，斜杠“/”的意思是“或”

**Comment by RyanY610** [comment]
谢谢

**Comment by RyanY610** [comment]
那是不是也可以用 --network "auto" 来代替？

**Comment by RyanY610** [comment]
好的👌🏻 了解

**Comment by leitbogioro** [comment]
装的速度有点慢罢了，快半个小时了，自己查查图里 IP 归属是不是 GCP，我可没诳你

![图片](https://github.com/leitbogioro/Tools/assets/22023450/06c3682f-fe07-49a8-bce2-363146e8b8f8)

**Comment by leitbogioro** [comment]
我装的 Debian 开机明显有个仪表版，方便查看机器运行状况：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/f1b1418e-c6a9-4045-8c4b-8c1b0032ff0e)

**Comment by RyanY610** [comment]
我知道  我两台机器都成功了

**Comment by RyanY610** [comment]
还是谢谢啦
