### ISSUE TITLE
ipv6网关无法识别

### ISSUE THREAD

**Issue by GreenTeodoro839** [leitbogioro/Tools#26]
idcwiki的机器，ipv6地址是公网，网关是fe80::1那样的，dd默认配置进live cd直接报错gateway unreachable，有没有办法解决？

**Comment by leitbogioro** [comment]
我都要被debian这个网关问题搞怕了，难受，加我tg联系吧，需要进机器里调试https://t.me/moricalau

**Comment by leitbogioro** [comment]
旧版的Debian对主ipv6地址、掩码、网关的处理支持可能不是特别好，我6月11日的时候帮一个朋友处理过idc.wiki家的纯ipv6机器，跟你的环境几乎一模一样，也是公网ipv6地址，fe80::1网关，64位掩码，当时我仅仅按此配置成功通过了Debian 12安装前的网络连通性检测，并未测试过Debian 11及以下版本的，这份是Debian 12重装后的网络配置，和原系统是一致的，敏感部分我做了特殊处理：

```
root@localhost:~# cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet6 static
	address 2405:e5a4:1:f01b::1/64
	gateway fe80::1
	# dns-* options are implemented by the resolvconf package, if installed
	dns-nameservers 2606:4700:4700::1001 2001:4860:4860::8844
	dns-search debian
```

**Comment by leitbogioro** [comment]
刚收了台idc.wiki的日本纯ipv6机器，装debian 12很明显能跑：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/34f910d9-cf3b-4a97-8ecf-e4226a5cf58d)

这是原系统的网络配置：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/b41e5b2f-c10f-43ef-910f-c62ea143e3ea)

旧版Debian为什么会出unreachable gateway我无法修正，这是Debian官方的问题，这也是他们为什么推出新版本来解决旧版本缺陷的原因，这不是我脚本有义务去解决的问题。

**Comment by GreenTeodoro839** [comment]
> 刚收了台idc.wiki的日本纯ipv6机器，装debian 12很明显能跑，纯ipv6栈，静态配置，公网ipv6地址，网关fe80::1，掩码64，跟你的环境完全一致：
> 
> 这是原系统的网络配置：
> 
> ![图片](https://user-images.githubusercontent.com/22023450/251720960-b41e5b2f-c10f-43ef-910f-c62ea143e3ea.png)
> 
> 这是安装Debian 12的阶段，很明显已经到了安装grub阶段，系统都快装完了：
> 
> ![图片](https://user-images.githubusercontent.com/22023450/251720489-34f910d9-cf3b-4a97-8ecf-e4226a5cf58d.png)
> 
> 旧版Debian为什么会出unreachable gateway我无法修正，这是Debian官方的问题，这也是他们为什么推出新版本来解决旧版本缺陷的原因，这不是我脚本有义务去解决的问题。

debian12可以进系统，但是不知道为什么ssh连不上，另一台没dd能连接

**Comment by GreenTeodoro839** [comment]
> 刚收了台idc.wiki的日本纯ipv6机器，装debian 12很明显能跑，纯ipv6栈，静态配置，公网ipv6地址，网关fe80::1，掩码64，跟你的环境完全一致：
> 
> 这是原系统的网络配置：
> 
> ![图片](https://user-images.githubusercontent.com/22023450/251720960-b41e5b2f-c10f-43ef-910f-c62ea143e3ea.png)
> 
> 这是安装Debian 12的阶段，很明显已经到了安装grub阶段，系统都快装完了：
> 
> ![图片](https://user-images.githubusercontent.com/22023450/251720489-34f910d9-cf3b-4a97-8ecf-e4226a5cf58d.png)
> 
> 旧版Debian为什么会出unreachable gateway我无法修正，这是Debian官方的问题，这也是他们为什么推出新版本来解决旧版本缺陷的原因，这不是我脚本有义务去解决的问题。

https://hostloc.com/thread-935655-1-1.html
参考一下这个，把网关改成ip去掉后面的1，我之前hk ipv6好像用moeclub脚本这么搞的
