### ISSUE TITLE
修改网卡参数导致有些情况小鸡失联，建议加个参数

### ISSUE THREAD

**Issue by tzeans** [leitbogioro/Tools#27]
使用DD脚本时候遇到修改网卡参数导致有些情况小鸡失联，研究了好久才发现是脚本配置的interfaces未加开启自动网卡参数，导致 一修改网络配置随机性就就直接失联，自己手动加个参数 auto 网卡就没有遇到了，希望作者改进下

**Comment by leitbogioro** [comment]
网卡参数不知道什么就不要改，不知道是什么改了反而出错，尤其是系统里被重定向过的网卡，就按eth0配置，不耽误你正常用

**Comment by leitbogioro** [comment]
就用 bash InstallNET.sh -debian 12 跑，如果出问题我来改，如果没有，是你自己指定网卡参数有问题，尤其是你并不知道系统中被重定向为eth0过后的网卡真名是什么，这不是我脚本应该做的工作。

**Comment by tzeans** [comment]
https://91ai.net/thread-840936-1-1.html
类这个帖子，主要这个网卡auto参数加和不加有差别吗，因为这个故障是随机性出现的搞得很头大我就建议下

**Comment by leitbogioro** [comment]
> https://91ai.net/thread-840936-1-1.html 类这个帖子，主要这个网卡auto参数加和不加有差别吗，因为这个故障是随机性出现的搞得很头大我就建议下

所以你的问题到底是自己删掉这个 auto，发现出了问题，然后改过来，发现问题消失，然后再把 auto 删了，发现又出问题，然后再改回来？于是循环往复？还是不动 interfaces 的任何参数，其实没有任何问题，但你非要改一下，显得“前辈”们的经验有用？

如果是前者，我觉得你有点作茧自缚。如果是后者，Debian系统下无论是用静态还是动态配置网络，配置每张网卡前 auto 参数必须添加，是不是觉得自己很懂？

**Comment by leitbogioro** [comment]
auto lo 表示自动配置本地回环（location）地址，allow-hotplug eth0（网卡名）表示配置热插拔网卡，这是Debian系统内配置网络参数的必备条件，是不是觉得把 allow-hotplug 网卡名改成 auto 就对了？你是相信Debian官方安装程序根据系统状况进行的最适合配置，还是业余的“前辈”们提供的过时经验？做人太聪明了反而不好。

`
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet6 static
	address 2b4f:a1c5:72:d4a0::1/64
	gateway fe80::1
	# dns-* options are implemented by the resolvconf package, if installed
	dns-nameservers 2606:4700:4700::1001 2001:4860:4860::8844
	dns-search debian
iface eth0 inet dhcp
`

**Comment by leitbogioro** [comment]
> https://91ai.net/thread-840936-1-1.html 类这个帖子，主要这个网卡auto参数加和不加有差别吗，因为这个故障是随机性出现的搞得很头大我就建议下

所以我需要了解的信息是安装好的系统如果你不去动它，它不出毛病，还是你手工改，它出了毛病？或者是你不动它，它出了毛病，得你手动干涉一下？如果是第一种情况，那不关我事；如果是第2种，那我觉得你还是自己想办法解决比较好；如果是第3种，这才是我需要去解决的事。

**Comment by leitbogioro** [comment]
如果装好的系统里这一部分配置内容如下，导致有时候机器重启后失联，那你把“allow-hotplug”改为auto，其他地方别动：

```
# The primary network interface
allow-hotplug 网卡名
```

**Comment by tzeans** [comment]
就是有时候会失联，我发现只要改网络配置，比如加一个虚拟网桥，增加一个IP 只要更新下小鸡马上就失联，确实修改为auto就不会了，为啥这样就不懂了

**Comment by tzeans** [comment]
因为我也是搞了好久才发现是这个auto的问题所以提个建议，怕有些人重蹈覆辙，如果改不了就算了，我自己手动改就可以

**Comment by leitbogioro** [comment]
> 就是有时候会失联，我发现只要改网络配置，比如加一个虚拟网桥，增加一个IP 只要更新下小鸡马上就失联，确实修改为auto就不会了，为啥这样就不懂了

原来你还要玩增加网桥这种操作，allow hotplug是Debian安装程序根据硬件状况自己做出的设置，原则上单机器单网卡情况下，这种设置是能保证计算机正常连接网络的，添加网桥的操作涉及到更改网络接口、更新ip配置等信息，这种配置是否还合适我就无法保证，双栈机单IPv4机IPv4配置部分，IPv6机IPv6配置部分存放在 /etc/network/interfaces 内的配置文件全是由Debian安装程序自动设定的，如果把它硬改成 auto 是否还适合默认环境下的机器网络状态，这个只能有待观察。

**Comment by leitbogioro** [comment]
这已经属于高阶网络配置的一个小技巧了，你可以写一份指南，来告诉别人搭建网桥的情况下，主网卡从allow hotplug改成auto更好，因为在有些情况下，主网卡硬改成auto也会引发一些不可预知的问题，你可以搜索“debian allow hotplug or auto”自行了解它们的区别。

**Comment by tzeans** [comment]
虚拟网桥很常见呀。nat小鸡 虚拟机 都有用到，多ip也会随机遇到失联，改不了就算了，我自己改也很简单，谢谢作者解答结贴。

**Comment by leitbogioro** [comment]
查了一下资料，auto 的含义是：

在系统启动的时候启动网络接口，无论网络接口有无连接 (插入网线) 。如果该接口配置了 DHCP，则无论有无网线，系统都会去获取 DHCP 。并且如果没有插入网线，则等该接口超时后才会继续 DHCP 。

allow-hotplug

只有当内核从网络接口检测到热插拔事件后才会启动该接口。如果系统开机时该接口没有插入网线，则系统不会启动该接口。系统启动后，如果插入网线，系统会自动启动该接口。

反正网上有关它们的区别说得很模糊，最重要的一点就是如果allow-hotplug加了手工配置，它在重启后就不能按预期能被正常启动，除非使用ifdown <网卡名> 和 ifup <网卡名>来重启，我尝试把默认的allow-hotplug统一改成auto，如果有大量反馈出问题，再改回来。

参考：

https://blog.csdn.net/xkq_lyx/article/details/17079849

https://blog.howesky.com/archives/20.html

**Comment by leitbogioro** [comment]
已经改过了，以DigitalOcean为例，新安装系统中网络配置为：

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet static
        address 143.198.109.106/20
        gateway 143.198.96.1
        # dns-* options are implemented by the resolvconf package, if installed
        dns-nameservers 1.0.0.1 8.8.4.4
        dns-search debian
iface eth0 inet6 static
        address 2604:a880:4:1d0::26e:d000
        netmask 64
        gateway 2604:a880:4:1d0::1
        dns-nameservers 2606:4700:4700::1001 2001:4860:4860::8844
```

网卡eth0为auto配置，可解决搭建网桥或添加更多ip导致的重启后失联问题。
