### ISSUE TITLE
纯IPV6服务器不能用，希望加入IPV6支持

### ISSUE THREAD

**Issue by wendadaya** [leitbogioro/Tools#3]
我有一台纯IPV6的vps，脚本提示：Error: Invalid network config
现在网上都没看到支持自动检测并配置好网络的纯IPV6服务器的一键DD脚本，希望作者可以添加这个功能

**Comment by leitbogioro** [comment]
已经支持纯 IPv6 机器了，在 Vultr 2.5$/m 纽泽西机器上实测过

**Comment by leitbogioro** [comment]
纯IPv6机器无论是动态还是静态IPv6都支持了，你可以试一下，没问题的话记得star，问题关闭了
