### ISSUE TITLE
Partitioning重大bug，自动把硬盘给格式化了。。。

### ISSUE THREAD

**Issue by jiangjiangflies** [leitbogioro/Tools#31]
我的NAS是mmc系统盘，然后有一块硬盘数据盘（sda），DD的时候居然把sda数据盘识别为系统盘格式化了...

**Comment by leitbogioro** [comment]
留下tg，私信联系

**Comment by leitbogioro** [comment]
脚本会默认把系统安装到连接到计算机的第一个可读写硬盘中，如果想指定脚本把系统装到哪个盘上，需要指定 -setdisk "硬盘名"，文档里有写，安装前屏幕上也会打印硬盘名，发现不对不能随意重启。

**Comment by jiangjiangflies** [comment]
加了-setdisk指定硬盘可以了。不过不可以让脚本自动识别dd前的系统硬盘吗？ 万一没注意把其他硬盘格式化的话损失就大了。还好这次我的硬盘没有太多东西，只是吃了个教训，没有损失太多。

**Comment by leitbogioro** [comment]
单盘没问题，多盘有点乏力，你原系统lsblk -ip是什么样的？

**Comment by jiangjiangflies** [comment]
![1690187171091](https://github.com/leitbogioro/Tools/assets/16556935/053162d3-3814-4ec1-b39b-fb11867df7fe)

**Comment by leitbogioro** [comment]
问题解决了，你可以不指定硬盘名试试，看看脚本是否能正常识别安装到 emmc 硬盘里，而非 sda
