### ISSUE TITLE
甲骨文 centos 7 执行命令 重启后 没有安装成功

### ISSUE THREAD

**Issue by yfnokmsn** [leitbogioro/Tools#32]
现在的系统是centos7，执行的安装命令是
bash InstallNET.sh -debian
命令执行后，提示reboot
输入reboot之后，系统还是之前的系统，而且硬盘占用增加了，不知道缓存文件在哪里？
现在不仅没有安装成功，硬盘也不知道如何清空了。。。

**Comment by leitbogioro** [comment]
检查一下：vim /etc/grub.d/40_custom ，看看有没有执行过其他重装脚本遗留下的错误启动项，导致启动失败，menuentry {} 的一堆菜单，如果有的话，全部删除，保存文件后，执行 grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg ，重新刷新一下 grub 引导，然后再执行脚本重装。

**Comment by leitbogioro** [comment]
我在甲骨文所有模版建立的干净机器上都测试过，是没有问题的

**Comment by leitbogioro** [comment]
刚开了一台甲骨文 AMD CentOS 7 的机器：

![](https://github.com/leitbogioro/Tools/assets/22023450/a3b312e5-267a-4307-90f4-f81764a52b45)

执行前重启：

![](https://github.com/leitbogioro/Tools/assets/22023450/0cc838fd-dca9-43d1-95a7-5b515ef097b1)

十来分钟后，系统安装成功，自己看看界面 IP 和第二张图一不一样，本脚本不负责替其他乱七八糟的残次品擦屁股，也不对用户自行修改了任何启动项负责：

![](https://github.com/leitbogioro/Tools/assets/22023450/23cfa5fc-8041-4f21-b4ef-35fa69dd23e8)

**Comment by yfnokmsn** [comment]
我再试试，多谢多谢

**Comment by yfnokmsn** [comment]
我的文件是这样的：
#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Install Debian bookworm amd64' --class debian --class gnu-linux --class gnu --class os {
  load_video
  set gfxpayload=text
  insmod gzio
        insmod part_gpt
        insmod xfs
        set root='hd0,gpt3'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt3 --hint-efi=hd0,gpt3 --hint-baremetal=ahci0,gpt3  f4a925ca-72d4-408e-bcca-1af1300ef953
        else
          search --no-floppy --fs-uuid --set=root f4a925ca-72d4-408e-bcca-1af1300ef953
        fi
  linuxefi /boot/vmlinuz auto=true  hostname=instance-20190917-2028 domain=debian quiet
  initrdefi /boot/initrd.img
}
~
----------------------------------------------------------
# Check Dependence

[ok]            awk
[ok]            basename
[ok]            cat
[ok]            cpio
[ok]            curl
[ok]            cut
[ok]            dig
[ok]            dirname
[ok]            file
[ok]            find
[ok]            grep
[ok]            gzip
[ok]            iconv
[ok]            ip
[ok]            lsblk
[ok]            openssl
[ok]            sed
[ok]            wget
[ok]            xz
find: ‘/proc/15030’: No such file or directory
find: ‘/proc/15278’: No such file or directory
find: ‘/proc/15369’: No such file or directory

# Network Details

[Adapter Name]  ens3
[Network File]  /etc/sysconfig/network-scripts/ifcfg-ens3
[Server Stack]  BiStack

[IPv4  Method]  isDHCP
[IPv4 Address]  10.0.0.4
[IPv4  Subnet]  255.255.255.0
[IPv4 Gateway]  10.0.0.1
[IPv4     DNS]  1.0.0.1 8.8.4.4

[IPv6  Method]  isStatic
[IPv6 Address]  2603:c021:8011:16ee:4c9e:7cb8:d4bc:4c94
[IPv6  Subnet]  64
[IPv6 Gateway]  fe80::200:17ff:fe90:896f
[IPv6     DNS]  2606:4700:4700::1001 2001:4860:4860::8844

# User Timezone

Asia/Shanghai

# SSH or RDP Port, Username and Password

22
root
LeitboGi0ro

# Installing Disks

/dev/sda

# Motherboard Firmware

UEFI

# Check DIST

Success

# Installation Starting

[Debian] [bookworm] [amd64] Downloading...
[Mirror] http://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
         http://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
268528 blocks

[Finish] Input 'reboot' to continue the subsequential installation.
[root@instance-20190917-2028 ~]# reboot
