### ISSUE TITLE
谷歌云dd windows 指定镜像链接或者指定版本都会失联

### ISSUE THREAD

**Issue by RyanY610** [leitbogioro/Tools#34]
bash InstallNET.sh --network "static" -windows 11

bash InstallNET.sh --network "static" -dd 'https://dl.lamp.sh/vhd/zh-cn_windows11_22h2_uefi.xz'
这两个都会失联

**Comment by leitbogioro** [comment]
新建机器的时候关闭安全启动，然后再试，如果还不行，说明dd包里可能不包含对应机型的硬盘或网卡驱动，此问题你需要向秋水逸冰反馈，我只能保证在普通机型上dd正常
