### ISSUE TITLE
可以支持 Windows 11/10 ARM 版的安装吗？

### ISSUE THREAD

**Issue by chenyuxiangyes** [leitbogioro/Tools#35]
如题，希望支持安装 ARM 版的 Windows，感谢大佬。

**Comment by leitbogioro** [comment]
Windows 超强的兼容性，就是来自基于 x86  x86_64 架构上开发的各种新老应用程序的支持，即使能在 arm 上安装专门为 arm 开发的 Windows ，除了 UI 界面和 x86 的 Windows 一致，很多 x86 的程序无法在 arm Windows 下兼容，除非再安装一个 x86 虚拟机来模拟运行，但运行效率相比在原生 x86 上运行降低 90% 也不是没有可能，目前为原生 arm Windows 开发的应用数量很有限，丰富程度甚至还不如 Linux，arm64 的机器还是用 arm64 Linux 比较好。

**Comment by leitbogioro** [comment]
需要的话可以去找找有谁做了相关 dd 包，然后通过 dd 包实现：

```
bash InstallNET.sh -dd 'windows 10 或 11 arm 版 dd 包 url'
```

**Comment by chenyuxiangyes** [comment]
嗯，dd包是.vhdx格式的吗？Windows的preview计划可以下载，我想加个密码之后导出成.vhdx格式。

**Comment by chenyuxiangyes** [comment]
奈何我没有能这么操作的设备，网上也找不到。

**Comment by leitbogioro** [comment]
> 嗯，dd包是.vhdx格式的吗？Windows的preview计划可以下载，我想加个密码之后导出成.vhdx格式。

要么你自己做，要么有别人做，目前支持解压的 dd 包压缩格式为 gzip 或 xzcat ，如果你自己做，手头没有 arm 的机器也很麻烦，x86 下有虚拟 arm CPU 的虚拟机软件吗？你可以自行研究一下。

**Comment by chenyuxiangyes** [comment]
感谢大佬的解答，我自己再好好研究一下。😄
