### ISSUE TITLE
how to support to install xfs system debian 11, now is ext4      /dev/sda1      ext4     959318096 1031228 909482468   1% /

### ISSUE THREAD

**Issue by 2837linlinlin** [leitbogioro/Tools#37]
root@device-6615:~# df -T
Filesystem     Type     1K-blocks    Used Available Use% Mounted on
udev           devtmpfs   8158240       0   8158240   0% /dev
tmpfs          tmpfs      1635220     608   1634612   1% /run
/dev/sda1      ext4     959318096 1031228 909482468   1% /
tmpfs          tmpfs      8176092       0   8176092   0% /dev/shm
tmpfs          tmpfs         5120       0      5120   0% /run/lock
tmpfs          tmpfs      1635216       0   1635216   0% /run/user/0
root@device-6615:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  608K  1.6G   1% /run
/dev/sda1       915G 1008M  868G   1% /
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.6G     0  1.6G   0% /run/user/0

**Comment by 2837linlinlin** [comment]
use
bash InstallNET.sh -debian 11

**Comment by leitbogioro** [comment]
You can assign -partition "gpt" to archive GPT partition, xfs file system for Debian series in target installation, for example:

```
bash InstallNET.sh -debian 11 -partition "gpt"
```
