### ISSUE TITLE
Can it support automatic reinstallation of proxmox 7.x system?

### ISSUE THREAD

**Issue by 2837linlinlin** [leitbogioro/Tools#38]
https://www.proxmox.com/en/downloads/proxmox-virtual-environment/iso/proxmox-ve-7-4-iso-installer

**Comment by leitbogioro** [comment]
I'm afraid not because my script aims to install a definite Linux or Windows OS on a server, not including any virtualization platform, if supported, it should be called as "PVE install".

**Comment by spiritysdx** [comment]
Maybe you need to try https://www.spiritlhl.net/en_US/guide/pve_precheck.html

**Comment by leitbogioro** [comment]
A good idea, but a bit difficult.
