### ISSUE TITLE
可以设置参数不加swap吗

### ISSUE THREAD

**Issue by BrunuhVille** [leitbogioro/Tools#4]
大佬您好
目前脚本重装会自动增加swap
可以设置参数不加吗
感谢

**Comment by leitbogioro** [comment]
swap 是系统自动分配的，在低内存机器上关闭可能会导致内存不足，启动失败，或者导致运行程序出现其他问题，况且永久关闭 swap 分区需要进新系统，编辑"/etc/fstab"文件，把带"swap"和带当前 UUID 的 swap 分区注释掉，比如:
UUID=6703c46c-8ab1-4bb2-a864-b5a2869364ad none            swap    sw              0       0
不同系统的硬盘分区 UUID 各不一样，preseed 阶段无法做到复杂的筛选判断逻辑， 所以你可以手动关闭。
