### ISSUE TITLE
dd完系统为什么硬盘会少了一个g

### ISSUE THREAD

**Issue by wisdomskip** [leitbogioro/Tools#40]
dd完系统为什么硬盘会少了一个g

**Comment by leitbogioro** [comment]
Debian 默认会多留 1GB 分区当做 swap，输入 lsblk -ip 或 df -Th 查看详情，如果还有疑问，把截图发过来看看

**Comment by wisdomskip** [comment]
![QQ浏览器截图20230906145613](https://github.com/leitbogioro/Tools/assets/141194436/de42a20f-b462-4423-ae65-6579ae915500)
上面是原来的系统，debian12
