### ISSUE TITLE
双栈多ip指定公网ip

### ISSUE THREAD

**Issue by qPB5dGJ** [leitbogioro/Tools#41]
抛砖引玉，双栈的示例写法好像还没人提过。特来请教。如果有192.168.0.100，10.0.0.200，2606:4700:4700::*/48，2001:4860:4860::*/48。脚本能直接填写吗？怎么填写？谢谢（网关都设为*::1）

**Comment by leitbogioro** [comment]
暂时是不行的，双栈配置每个对应的 IP 栈只能给一个，分别对应 IPv4 和 IPv6 ，否则参数给太多了不好处理

**Comment by qPB5dGJ** [comment]
双栈写法能给个模板吗？假设ipv4是/24和ipv6是/64。后人只需要照抄就可以。THX

**Comment by leitbogioro** [comment]
IPv4 栈 IPv6 栈如果要启用哪个，哪个栈的 IP 地址、网关、子网掩码这一套必须要指定。

```
bash InstallNET.sh -debian 12 --ip-addr "1.2.3.4" --ip-gate "1.2.3.1" --ip-mask "24" --ip6-addr "2606:4700:4700::10" --ip6-gate "2606:4700:4700::1" --ip6-mask "64"
```
