### ISSUE TITLE
SSH欢迎页sys info

### ISSUE THREAD

**Issue by qPB5dGJ** [leitbogioro/Tools#45]
没找到修改日志。部分机器重装后会出现sys info部分不会。不知道是项目修改还是别的原因导致。如有可能的话给个参数选项。不安装并信任第三方面板的情况下SSH直接显示sys info还是有用的

**Comment by leitbogioro** [comment]
有很多人说不需要，而且国内机器显示时由于需要查询Google的dns，会造成ssh登陆时卡顿，所以默认隐藏了，可以添加 --motd 参数预置，仅适用于Debian/Kali/AlpineLinux ，使用方法如：
```
bash InstallNET.sh -debian 12 --motd
```

**Comment by qPB5dGJ** [comment]
查询google导致的卡顿确实难以避免，也没有那么多可以信任的平替。多嘴一句，我探针用的比较少，既然一般是服务器在没有gui的情况下用脚本重装冰期待SSH返回欢迎页。为什么不考率直接读取网卡信息？业务性的代理应该使用TLS或组件的VPN私网。通用的更换ip的代理应该由客户端确认出口。我觉得知道网卡声明了什么信息对一般用户足够了，起到一个明确自己登录了哪台小鸡的作用而不用查看SSH客户端的nick name甚至详细设置。
以上
