### ISSUE TITLE
腾讯l轻量云debian12下无法重装

### ISSUE THREAD

**Issue by haodiao** [leitbogioro/Tools#46]
腾讯l轻量云debian12下无法重装，只能重装回腾讯轻量云的debian11后，再在debian11下使用这个一键重装才能正常

**Comment by leitbogioro** [comment]
我在腾讯云上用后台模板的Debian 12测试时也发现了这个问题，初步发现原因是原系统虽然写入了正确的grub引导，但系统重启后并未发现有grub菜单选项，并自动倒计时进入新系统安装，这个问题仅在腾讯云自带的Debian 12上出现，它自带的OpenCloudOS 8.6，CentOS 7.6，CentOS stream 8，Debian 10/11，Ubuntu 18.04/20.04/22.04上均未发现此问题，说明腾讯云自带的Debian 12镜像有问题，后续需要进一步排查。

**Comment by leitbogioro** [comment]
我已经发工单向腾讯云技术人员反馈了这个问题，如果他们不重新制作能由修改grub启动自定义启动项的debian 12模板，重装前请选择以其他版本建立系统

**Comment by leitbogioro** [comment]
咨询过腾讯云官方客服，得到的结果是只要卸载掉“kexec-tools”组件，即可从 grub 正确引导脚本写入的菜单选项。以下是咨询详情：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/6a7d28bf-1df6-4ee9-88df-e32e5fccf739)

添加了卸载“kexec-tools”组件后，脚本执行卸载相关组件和最终运行结果如图所示：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/0b66cef1-2f5c-4e0d-a812-149d4810947e)

![图片](https://github.com/leitbogioro/Tools/assets/22023450/182dc573-c704-4812-a530-de14b4b503df)

在腾讯云后台自带模板系统 Debian 12 中写入的安装纯净 Debian 12 grub 引导菜单项：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/e68e789e-87b0-4458-9446-d52b651dd6fa)

实测后发现在腾讯云自带模板系统 Debian 12 中卸载掉该组件，重启后确实能够从自定义 grub 引导启动并顺利重装到脚本支持的系统：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/04151a20-2ffc-41a7-9b30-de40cc6e7ded)

最后安装结束，重启，ssh 连接脚本安装好后的新系统的画面：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/b5764496-67d1-4a87-afe0-778aaca6ba19)

我这边实测没问题，如果你有条件，也可以复现一下我以上所提及的步骤，然后反馈结果。

**Comment by leitbogioro** [comment]
咨询过腾讯云官方客服，得到的结果是只要卸载掉“kexec-tools”组件，即可从 grub 正确引导脚本写入的菜单选项。以下是咨询详情：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/6a7d28bf-1df6-4ee9-88df-e32e5fccf739)

添加了卸载“kexec-tools”组件后，脚本执行卸载相关组件和最终运行结果如图所示：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/0b66cef1-2f5c-4e0d-a812-149d4810947e)

![图片](https://github.com/leitbogioro/Tools/assets/22023450/8caaa617-538b-4576-9ab5-9af4bd70ee1a)

在腾讯云后台自带模板系统 Debian 12 中写入的安装纯净 Debian 12 grub 引导菜单项：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/e68e789e-87b0-4458-9446-d52b651dd6fa)

实测后发现在腾讯云自带模板系统 Debian 12 中卸载掉该组件，重启后确实能够从自定义 grub 引导启动并顺利重装到脚本支持的系统：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/04151a20-2ffc-41a7-9b30-de40cc6e7ded)

最后安装结束，重启，ssh 连接脚本安装好后的新系统的画面：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/b5764496-67d1-4a87-afe0-778aaca6ba19)

我这边实测没问题，如果你有条件，也可以复现一下我以上所提及的步骤，然后反馈结果。
