### ISSUE TITLE
腾讯云 ubuntu22.04  一键重装 卡引导界面

### ISSUE THREAD

**Issue by linai081795** [leitbogioro/Tools#47]
![image](https://github.com/leitbogioro/Tools/assets/12321385/685bf040-bf18-4185-a16c-d4c17a9a0ea3)
vnc 卡住后 后续无法操作

**Comment by linai081795** [comment]
腾讯云 云服务器 非轻应用服务器

**Comment by leitbogioro** [comment]
此过程是正在从我存储Ubuntu镜像的服务器拉起镜像并dd到本地，国内服务器连接国外速度较慢，dd过程可能会花费较长时间，请耐心等待镜像下载dd完成，极端情况下安装过程可能会持续半天左右甚至更久

**Comment by leitbogioro** [comment]
Ubuntu 22.04以后由于无法使用原来的，在内存中启动网络内核启动并原生方式安装，所以现在实现安装的手段是先启动中介系统AlpineLinux，然后把远程服务器中经过处理的Ubuntu镜像直接dd到硬盘里实现安装，具体原理参见：

https://www.nodeseek.com/post-9558-1

如果你想自制镜像，也可以按帖子里的方法自行打包，并把镜像存储在一个连接你服务器更快的空间内，然后指定 --image 参数进行安装加速：

```
bash InstallNET.sh -ubuntu 22.04 --image '你用来存储Ubuntu dd 镜像的 url'
```

如果无意自建镜像源、自制 dd 包加速，且对脚本内置源速度不满意或对脚本内置源镜像安全性有质疑，请采用其他手段，自行安装 Ubuntu

**Comment by leitbogioro** [comment]
Ubuntu 22.04 以后由于无法使用原来的，在内存中启动网络内核启动并原生方式安装，所以现在实现安装的手段是先启动中介系统 AlpineLinux，然后把远程服务器中经过处理的 Ubuntu 镜像直接 dd 到硬盘里实现安装，具体原理参见：

https://www.nodeseek.com/post-9558-1

如果你想自制镜像，也可以按帖子里的方法自行打包，并把镜像存储在一个连接你服务器更快的空间内，然后指定 --image 参数进行安装加速：

```
bash InstallNET.sh -ubuntu 22.04 --image '你用来存储Ubuntu dd 镜像的 url'
```

如果无意自建镜像源、自制 dd 包加速，且对脚本内置源速度不满意，或对脚本内置源镜像安全性有质疑，请停止使用本脚本，采用其他手段，自行安装 Ubuntu
