### ISSUE TITLE
-pwd 参数无效

### ISSUE THREAD

**Issue by 12189108** [leitbogioro/Tools#49]
```
bash InstallNET.sh -ubuntu 22.04 -pwd 'password'
```
我使用了上述命令，但密码总是默认的，不是我设定的

**Comment by leitbogioro** [comment]
因为安装Ubuntu是从alpine Linux里dd的，变量需要进行二次传递和替换，sed在处理字符串替换的时候，遇到特殊符号根本无法处理，进而导致设置的密码失效，重装后无法进入系统，所以密码暂不支持自定，端口可以自定
