### ISSUE TITLE
有個雞失聯了，可以直接格式化然後DD到這個硬碟嗎?

### ISSUE THREAD

**Issue by Georgebobby** [leitbogioro/Tools#50]
首先衷心感謝您提供的版本，讓還在學習的我，可以盡情胡搞~~ XD
如題，雞被玩壞了，可以ISCSI到好的雞然後DD新的系統，然後attach回嗎?
謝謝~

**Comment by leitbogioro** [comment]
能重装的前提是机器上必须有正在正常运行的Linux系统，如果是救砖，请自行制作适合的救砖包，然后挂载在其他机器上把系统用dd命令写入
