### ISSUE TITLE
Cannot install on oracle cloud

### ISSUE THREAD

**Issue by macosupdate** [leitbogioro/Tools#51]
I have 4 orcacle cloud vps, 3 installed successfully. Only 1 vps failed, the file finished running, rebooted, but the operating system remained the same. I tried again several times, changing the Debian version
How can I report a bug to you? If you have a private communication channel or email, I will send you the vps login information

**Comment by leitbogioro** [comment]
Maybe the environment of the original system has been changed, I'm always recommend you to reinstall to the new system by this script in a clean original system. If it's still failed, you may delete it and rebuild a new one to continue to installation only, I tested on CentOS AlmaLinux RockyLinux Ubuntu Oracle Linux which templates are provided by Oracle Cloud and found no problem.

**Comment by leitbogioro** [comment]
Sorry, there were certainly some bugs in the script to set the grub wrong with Redhat series and I resolved it, the following steps may suitable for you to make troubleshootings:

1. Delete all menuentries in this file that script wrote:

```
/etc/grub.d/40_custom
```

2. Update grub:

```
grub2-mkconfig
```

And then execute script again.
