### ISSUE TITLE
oracle linux8 命令开始后有3行说命令没发现.. 有没有影响?倒也能dd成功

### ISSUE THREAD

**Issue by 142857X1** [leitbogioro/Tools#52]
[root@forko1 ~]# bash <(curl -sSL https://raw.githubusercontent.com/leitbogioro/Tools/master/Linux_reinstall/InstallNET.sh) -ubuntu 20.04 
Setting up swapspace version 1, size = 512 MiB (536866816 bytes)
no label, UUID=ffa4f9a5-c1ef-4d83-9e56-cd9613df28a0
sed: can't read /etc/apt/sources.list: No such file or directory
/dev/fd/63: line 1091: apt: command not found
/dev/fd/63: line 1094: apt: command not found
/dev/fd/63: line 1110: apt: command not found
Ksplice for Oracle Linux 8 (x86_64)                                                                                                                                 7.8 MB/s | 3.7 MB     00:00    
MySQL 8.0 for Oracle Linux 8 (x86_64)                                                                                                                               9.8 MB/s | 3.0 MB     00:00    
MySQL 8.0 Tools Community for Oracle Linux 8 (x86_64)                                                                                                               1.3 MB/s | 491 kB     00:00    
MySQL 8.0 Connectors Community for Oracle Linux 8 (x86_64)

**Comment by leitbogioro** [comment]
不影响，apt 命令是 Debian 系用于安装必要前置组件的命令，Oracle Linux 属于红帽系，所以不适用于运行 apt 命令。
