### ISSUE TITLE
在非空目录执行会卡住

### ISSUE THREAD

**Issue by lushdog** [leitbogioro/Tools#54]
在/root文件夹内 执行命令`bash InstallNET.sh -debian` ，发现会卡在 grep -wrl 'iface'命令。
只能把脚本移动到空文件夹执行。

**Comment by leitbogioro** [comment]
已设置超时自动跳过：https://github.com/leitbogioro/Tools/commit/b063db52e350f20cd2f3653ce8916bbb2cf0a005
