### ISSUE TITLE
脚本需要768M内存才能运行

### ISSUE THREAD

**Issue by rpwtinfo** [leitbogioro/Tools#55]
emmm，但是我dd alpine的原因就是因为内存不够（只有200M）。。。所以就陷入了一个死循环。有办法降低内存需求吗？谢谢

**Comment by leitbogioro** [comment]
200m 啥也装不了，只能用面板自带的了，这确实没有办法

**Comment by leitbogioro** [comment]
我稍后在文档里更新一下安装各不同系统的基准内存需求

**Comment by leitbogioro** [comment]
代码更新了，试试看 AlpineLinux 能不能装，内存容量 256M 是底线

**Comment by rpwtinfo** [comment]
可以装了，实测230多M的内容也可以正常安装~~
