### ISSUE TITLE
cant reinstall to centos8

### ISSUE THREAD

**Issue by saobilin** [leitbogioro/Tools#56]
test system:debian11 debian12 Centos7
vps mem low than 4G,use --nomemcheck
![1](https://github.com/leitbogioro/Tools/assets/50769148/79bf0f1f-3efa-4bea-8c87-88ef1654006d)

**Comment by leitbogioro** [comment]
Any server that has lower memory than 2.2G will cause native installation of CentOS stream 8 failed, try to cancel to adding "--nomemcheck", Linux install will switch to try to install RockyLinux 8 to instead.

**Comment by leitbogioro** [comment]
All distributions of Redhat 8 series are not recommend in principle, higher memory requirements for installing, worse compatibility, 9 series is a better choice.

**Comment by madlaxcb** [comment]
> Any server that has lower memory than 2.2G will cause native installation of CentOS stream 8 failed, try to cancel to adding "--nomemcheck", Linux install will switch to try to install RockyLinux 8 by overwriting cloud image mode to instead.

试了几次重装centos 8 stream都变成rocky8，才找到这来，希望能在readme的centos项下添加说明。
