### ISSUE TITLE
BBQL

### ISSUE THREAD

**Issue by Doutianbao** [leitbogioro/Tools#57]
甲骨文，一个arm，一个AMD
dd安装ubuntu 22.04，目前都无法使用ssh链接。。。。

**Comment by Doutianbao** [comment]
要哭死在github   - -

**Comment by leitbogioro** [comment]
我用两台甲骨文arm机器测试过，一台ipv4单栈，一台双栈，刚做过重装测试，均未遇到过你所述问题：

![74AF547A-C091-4DE8-987B-E6F706AD9215](https://github.com/leitbogioro/Tools/assets/22023450/c0248bbf-d875-4f0e-922a-f19102c303a1)

![269FB3EE-AA0F-44FD-8524-93D29C4E9B3C](https://github.com/leitbogioro/Tools/assets/22023450/547d8e66-4ad2-4b31-b51c-2eb11a47e2c9)

![F7E09C7D-42C1-4754-A7F5-0645CB02D817](https://github.com/leitbogioro/Tools/assets/22023450/c0d27b3a-b942-4bcb-b4ab-2be848259322)

现在机器能连接 vnc吗？看看vnc里是什么情况

**Comment by leitbogioro** [comment]
通过 dd cloud image 安装的系统初始密码无法提前预置，用 LeitboGi0ro 连接试试

**Comment by Doutianbao** [comment]
这么说我这回事凉透了。
因为reboot很久后还没有反应才发的issue

**Comment by leitbogioro** [comment]
amd机器上也从不同商家不同初始系统模板做过大量测试，也未发现重装后ssh无法连接的情况

**Comment by Doutianbao** [comment]
现在是ssh根本无法连接

**Comment by leitbogioro** [comment]
有tg吗？发一下我加你

**Comment by Doutianbao** [comment]
t.me/hbykdx

**Comment by Doutianbao** [comment]
hbykdx

**Comment by leitbogioro** [comment]
该问题由于无法稳定复现，暂时关闭，有问题私聊解决
