### ISSUE TITLE
[Warning] Only accept prefix format of IPv4 address, length from 1 to 32.

### ISSUE THREAD

**Issue by Rizz-Code** [leitbogioro/Tools#62]
what is the correct command if I set the IP address, I always get the message [Warning] Only accept prefix format of IPv4 address, length from 1 to 32. or [Error] Invalid inputted IPv4 format!

my command bash InstallNET.sh -dd "https://xxxx.my.id/xxxx.gz" -filetype "gz" -timezone "Asia/Jakarta" --ip-addr 134.122.126.183 --ip- mask 255.255.240.0 --ip-gate 134.122.112.1

**Comment by leitbogioro** [comment]
Here is the IPv4 calculator:

https://www.vultr.com/resources/subnet-calculator/

The prefix of 255.255.240.0 is 20 absolutely.

**Comment by leitbogioro** [comment]
The sample of calculating 1.6.6.6/20

CIDR Notation
1.6.0.0/20

Address Range
1.6.0.0 - 1.6.15.255

Mask Bits
20

Subnet Mask
255.255.240.0

**Comment by Rizz-Code** [comment]
Thanks bro

**Comment by Rizz-Code** [comment]
on digitalocean I installed windows with this command, but why doesn't the network driver match the settings in the command, it's still dhcp

**Comment by leitbogioro** [comment]
The default network configure method of dd image may dhcp but the upstream network configure method of Digital Ocean is static, so you should login the system by VNC and configure static manually by yourself.

**Comment by leitbogioro** [comment]
If you use "bash InstallNET.sh -windows" to install Windows, when you login system by VNC first, there is a script to set static network automatically.

**Comment by Rizz-Code** [comment]
oke bro thanks for information
