### ISSUE TITLE
哥，一键DD了，咋都连不上，都是提示登录失败

### ISSUE THREAD

**Issue by weiyunkj666** [leitbogioro/Tools#64]
试了默认密码也不对，我自定义的密码，也不对，折腾我两天了，这玩意还没重装的，救救我....这玩意也没有公网IP

https://i1.wp.com/img.erpweb.eu.org/imgs/2023/11/72b5c5c3a920244a.png

**Comment by weiyunkj666** [comment]
试了一晚上了，之前也遇到这种问题，以为是我重装的时候密码输入错误了，但我截图了，现在还是登录不进去

**Comment by leitbogioro** [comment]
测试了一下，装 Debian 11，密码设置为 “123@@@”，运行命令：

```
bash InstallNET.sh -debian 11 -pwd '123@@@'
```

![图片](https://github.com/leitbogioro/Tools/assets/22023450/ee6ec872-43e7-4ed9-8e46-d93056b8a6d4)

![图片](https://github.com/leitbogioro/Tools/assets/22023450/c8097bff-b0db-4f2b-917b-6595b38ef351)

![图片](https://github.com/leitbogioro/Tools/assets/22023450/eedd74f4-ec36-47a1-b347-d16c77c087b7)

![图片](https://github.com/leitbogioro/Tools/assets/22023450/b47f749a-7260-4264-b3f6-c49946c6fef3)

系统能进，没发现问题。

**Comment by weiyunkj666** [comment]
哥，我知道，我一直用你的脚本，但这个移动云电脑有点奇怪，我遇到好几次了这样登录不进去了，哥，除了登录还有没有其他的办法？这电脑不能重装，想哭，哥，如果有其他办法，可以尽全力配合你，救救我

**Comment by leitbogioro** [comment]
> 哥，我知道，我一直用你的脚本，香港啥的国外或者其他地区机器，用你这从来没这样过，这个移动云电脑有点奇怪，我遇到好几次了这样登录不进去了，哥，除了登录还有没有其他的办法？这电脑不能重装，想哭，哥，如果有其他办法，可以尽全力配合你，救救我

这东西自带只有Windows系统，想装Linux必须从Windows装过去，你应该是用别的脚本完成的，但我听论坛里说即使装成了Linux，从Linux再安装成Linux还是有问题，我手上也没有这个产品，不清楚原因是什么

**Comment by weiyunkj666** [comment]
> > 哥，我知道，我一直在用你的剧本，香港啥的国外或者其他地区的机器，你从来没有这样过，这个移动云电脑有点奇怪，我遇到好几次这样登录不进去了，哥，除了登录还有没有其他的办法？这电脑不能重装，想哭，哥，如果有其他的办法，可以尽全力打你，救救我
> 
> 这东西自带只有Windows系统，想装Linux必须从Windows装过去，你应该是用其他完成脚本的，但我听论坛里说即使装成了Linux，从Linux再安装Linux还是有问题，我手上也没有这个产品，节日原因是什么，没办法，你不如联系客服让他们给个能重装成Linux的功能

是的，这玩意只有windows,先用其他脚本装成Alpine，再从Alpine装成debian，我另外一台就正常登录，这台死活不行，看来只能找客服看看有没有其他解决办法了，现在只能选择内核启动与安全模式，每一步都需要密码，可是输入密码都不正确，无法进入系统，哥，对不起，这么晚了打扰你了

**Comment by leitbogioro** [comment]
让客服重置系统，然后再重复重装步骤，唯一的区别是从 alpine 重装到 debian 时，使用 --network "static" 强制使用静态方式配置网络，因为我看论坛里有人发帖说这个云电脑 dhcp 不稳定，有一定概率掉，以及重装时先别自定密码，确认能 ssh 登陆后再改。
