### ISSUE TITLE
External Script Contains DOS Line Breaks

### ISSUE THREAD

**Issue by PhoenixEmik** [leitbogioro/Tools#65]
https://github.com/leitbogioro/Tools/blame/1abd25f577a31282549649fb35870d98833dfa9a/Linux_reinstall/InstallNET.sh#L1181
![圖片](https://github.com/leitbogioro/Tools/assets/10204811/a5968b1e-ce2c-4788-8f7b-8b887efb6550)

Only the script downloaded from Gitee has this issue.

**Comment by leitbogioro** [comment]
It may caused by incorrect space character.

**Comment by PhoenixEmik** [comment]
![圖片](https://github.com/leitbogioro/Tools/assets/10204811/85f9bf49-76ef-4a2c-b5b1-29ccfb7ec43b)
Converting this script by using dos2unix fixes this issue.

**Comment by leitbogioro** [comment]
I reloaded the file to gitee.com mirror and it works now.

![图片](https://github.com/leitbogioro/Tools/assets/22023450/96de688f-9c3a-4815-bb83-402624fdc3ec)

**Comment by PhoenixEmik** [comment]
Thanks.
