### ISSUE TITLE
改出问题了，用不了了，兄弟

### ISSUE THREAD

**Issue by gimgoo** [leitbogioro/Tools#67]
![image](https://github.com/leitbogioro/Tools/assets/31849284/9ee02824-d24b-4a6b-a920-6a14bfe7e8f7)

**Comment by leitbogioro** [comment]
估计是当前系统里有一些组件或者环境变量不对，如果能用后台重装功能，换个系统试试，不行的话留个tg，我去你环境里看看它脚本在标准环境下运行是没问题的
