### ISSUE TITLE
阿里云 ubuntu 22.04 install failed 

### ISSUE THREAD

**Issue by ivanberry** [leitbogioro/Tools#73]
bash InstallNET.sh -ubuntu

进入了grub rescue。查询一些资料时，需要用到fdisk 等工具，但是都没有对应的命令。

**Comment by leitbogioro** [comment]
机器是中国大陆境内还是境外？需要提供 vnc 截图

**Comment by ivanberry** [comment]
<img width="569" alt="image" src="https://github.com/leitbogioro/Tools/assets/13112910/70e30d74-ef0f-40e5-ae5a-eb0540303d01">

阿里云，国内

**Comment by leitbogioro** [comment]
国内连接源下载速度太慢，导致系统包长时间下载不完，建议做个反代加速，或者安装 Debian，或者使用其他同类脚本
