### ISSUE TITLE
双网卡dd不太友好

### ISSUE THREAD

**Issue by jh0072110** [leitbogioro/Tools#78]
在dd debian/kali时没有什么问题
cent/alma/ubuntu就会抽风 dd结束后无法联网（虽然自己在VNC里可以改改但是…嗯哈哈哈哈）

**Comment by leitbogioro** [comment]
多网卡难搞，对 debian/kali 的多网卡优化是特化的，其他系统主要是我自己平时不怎么用，所以这种极特殊情况下只能麻烦一些

**Comment by leitbogioro** [comment]
还有极少数独服采用的网络连接方式是把多张物理网卡绑定起来，在系统层面抽象成一张虚拟的网卡接口，以充分利用多网卡带宽叠加的优势，比如 bond0 ，这种情况下如果从 netboot 内核启动安装，只能选择先配置单网卡联网，但 bond0 情况下的网络配置参数可能不适用于配置多网卡中的某一个，从而联网失败，即使成功，还要在安装后续写下配置文件，把它们再组合成那个 bond0 ，从实现的复杂程度和这种情况的占比来看，不值得

**Comment by jh0072110** [comment]
> 多网卡难搞，对 debian/kali 的多网卡优化是特化的，其他系统主要是我自己平时不怎么用，所以这种极特殊情况下只能麻烦一些

debian/kali在两个以上网卡的情况下也败下阵来…

**Comment by leitbogioro** [comment]
> > 多网卡难搞，对 debian/kali 的多网卡优化是特化的，其他系统主要是我自己平时不怎么用，所以这种极特殊情况下只能麻烦一些
> 
> debian/kali在两个以上网卡的情况下也败下阵来…

这种情况出现的概率太低了，我现在还没遇到过
