### ISSUE TITLE
建议可以给预置组件设置一个参数开关

### ISSUE THREAD

**Issue by CeeIM** [leitbogioro/Tools#8]
预置的常用组件、彩色显示、欢迎画面，建议能在 DD 的时候添加一个参数来决定是否预装或者是原版纯净系统。
因为有的机型配置实在比较低，也用不到一些组件，希望会有一个参数开关比较好。
例如：
`bash InstallNET.sh -debian -pure`

默认打开或者默认关闭都没所谓，应该有人和我一样需求？（我认为

**Comment by leitbogioro** [comment]
预置组件深度嵌到脚本里了，给个开关还得独立出来，懒得改了
