### ISSUE TITLE
甲骨文dd ubuntu 22.04失败（含错误截图）

### ISSUE THREAD

**Issue by 12189108** [leitbogioro/Tools#82]
![捕获](https://github.com/leitbogioro/Tools/assets/24732116/893ea899-2508-4318-9b29-a34ba0199988)

到这部就进行不下去了，后面会跳回选择系统的界面，但**不会自动选择系统**，这就是为什么会失联，手动进入系统后还是未dd状态

![捕获](https://github.com/leitbogioro/Tools/assets/24732116/183d6a8f-9fdb-4e13-ba1a-f90c65968316)

**Comment by 3377** [comment]
兄弟，跟你一样，如何解决的

**Comment by 12189108** [comment]
> 兄弟，跟你一样，如何解决的

解决不了一点，解决了这个issue就不是open了

**Comment by leitbogioro** [comment]
从CentOS 7启动Alpine edge(3.20): errors invalid magic number，必须要先安装Alpine 3.18，才能安装更高版本Alpine或从Alpine引导dd安装其他系统

**Comment by 3377** [comment]
![photo_2024-03-07_14-40-20](https://github.com/leitbogioro/Tools/assets/15319161/5fe24fe1-8aba-4d10-be06-cd5cce46f808)
问题他不是centos7启动啊，当前系统是ubuntu20.04，打算DD成干净的20.04，然后D了6次，开机就出现上图这样，如果不手动选择的话机器就启动不了。

**Comment by leitbogioro** [comment]
此问题是alpinelinux 3.19及以后版本的系统，默认采用grub 2.12，其中的fwsetup --is-supported语法旧版本grub 2.06不兼容导致的，已测试的原系统Ubuntu 22.04及之前、红帽全系，通过引导AlpineLinux netboot文件安装AlpineLinux 3.19+, edge，或以AlpineLinux为媒介，实行dd安装的任何系统，都会出问题。

Debian 12经测试未发现此问题，可正常启动。

该情况仅在arm64机型上出现，amd64并未受到影响。

解决方法是使用OpenSUSE的tumbleweed分支的grub.efi植入并替换掉原系统中/boot/efi/EFI/系统名/grubaa64.efi文件即可解决，在原系统为CentOS 7，RockyLinux 9上测试过重装为Ubuntu 22.04，Ubuntu 24.04，并且从Ubuntu重装至AlpineLinux都已经成功了，代码稍后更新。

**Comment by leitbogioro** [comment]
从Ubuntu 22.04(grub 2.06) 引导AlpineLinux edge(3.20, grub 2.12)启动：

![6411b266f01f04e806be58901e925b3](https://github.com/leitbogioro/Tools/assets/22023450/0f64c7dc-e375-4a2a-ab40-5369be261990)

![1709823278458](https://github.com/leitbogioro/Tools/assets/22023450/27b03e24-cddf-480e-b18d-c7f30e6ac03b)

从RockyLinux(grub 2.06) 引导到AlpineLinux edge并安装：

![ccdd5f754947cdd0f46320d14a1e3ab](https://github.com/leitbogioro/Tools/assets/22023450/244df784-f1cf-4e57-893d-6634fdfb09b5)

![1709823512576](https://github.com/leitbogioro/Tools/assets/22023450/40e04342-44ff-4198-9e00-d53cb5741ee0)

从CentOS 7引导到AlpineLinux edge并安装Ubuntu 24.04：

![bae653f283db5fcbeb11e2a49029922](https://github.com/leitbogioro/Tools/assets/22023450/4ec0537e-525d-49c8-b83e-11a55d45ba82)

![3e23ab0af575daa30dd66a3e70fee2d](https://github.com/leitbogioro/Tools/assets/22023450/c21b6bf8-beac-4468-b01c-4944f64ef0c2)

![1a8ff680efcf038c73009d7d3af5c67](https://github.com/leitbogioro/Tools/assets/22023450/7806b3ff-d034-4940-acf7-d9ce04623f6e)

![de751deb94eb012ca3a027454aeb16c](https://github.com/leitbogioro/Tools/assets/22023450/b153a56d-d273-4a06-b08b-ab1d47c56fcf)

从Ubuntu 22.04(grub 2.06)安装到Ubuntu 24.04(grub 2.12)：

![a45716542059bfada68cafdbb8c32e0](https://github.com/leitbogioro/Tools/assets/22023450/d7ab7682-71a4-4b11-91eb-04b50bae76fd)

![98d0fa6aa0fd37d770b798f6dca981b](https://github.com/leitbogioro/Tools/assets/22023450/7118f04c-ff89-41b9-8995-13d7de34d55e)

**Comment by leitbogioro** [comment]
从Ubuntu 22.04(grub 2.06) 引导AlpineLinux edge(3.20, grub 2.12)启动：

![6411b266f01f04e806be58901e925b3](https://github.com/leitbogioro/Tools/assets/22023450/0f64c7dc-e375-4a2a-ab40-5369be261990)

![1709823278458](https://github.com/leitbogioro/Tools/assets/22023450/27b03e24-cddf-480e-b18d-c7f30e6ac03b)

从RockyLinux(grub 2.06) 引导到AlpineLinux edge并安装：

![ccdd5f754947cdd0f46320d14a1e3ab](https://github.com/leitbogioro/Tools/assets/22023450/244df784-f1cf-4e57-893d-6634fdfb09b5)

![1709823512576](https://github.com/leitbogioro/Tools/assets/22023450/40e04342-44ff-4198-9e00-d53cb5741ee0)

从CentOS 7引导到AlpineLinux edge并安装Ubuntu 24.04：

![bae653f283db5fcbeb11e2a49029922](https://github.com/leitbogioro/Tools/assets/22023450/4ec0537e-525d-49c8-b83e-11a55d45ba82)

![3e23ab0af575daa30dd66a3e70fee2d](https://github.com/leitbogioro/Tools/assets/22023450/c21b6bf8-beac-4468-b01c-4944f64ef0c2)

![1709824000662](https://github.com/leitbogioro/Tools/assets/22023450/538dc434-572b-4836-8b5d-3cf7b9e540e6)

![de751deb94eb012ca3a027454aeb16c](https://github.com/leitbogioro/Tools/assets/22023450/b153a56d-d273-4a06-b08b-ab1d47c56fcf)

从Ubuntu 22.04(grub 2.06)安装到Ubuntu 24.04(grub 2.12)：

![a45716542059bfada68cafdbb8c32e0](https://github.com/leitbogioro/Tools/assets/22023450/d7ab7682-71a4-4b11-91eb-04b50bae76fd)

![98d0fa6aa0fd37d770b798f6dca981b](https://github.com/leitbogioro/Tools/assets/22023450/7118f04c-ff89-41b9-8995-13d7de34d55e)

**Comment by 3377** [comment]
能指导一下那些错误的引导项怎么删除吗、现在重启机器必须进控制台选择一下才能进去

**Comment by leitbogioro** [comment]
> 能指导一下那些错误的引导项怎么删除吗、现在重启机器必须进控制台选择一下才能进去

Debian/Ubuntu/AlpineLinux在/boot/grub/grub.cfg里：把menuentry {*} 部分删除即可，不需要刷新grub：

![图片](https://github.com/leitbogioro/Tools/assets/22023450/439898df-e3ad-4255-90b6-57dd44aab1e3)

CentOS 7在/boot/efi/EFI/centos/grub.cfg里，

CentOS 9, RockyLinux AlmaLinux在/boot/grub2.grub.cfg里，但修改新启动项要在/etc/grub.d/40_custom里改。

红帽系改完了需要刷新grub引导：

grub2-mkconfig -o 'grub.cfg文件所在位置'
